---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 86181.
--- DateTime: 2021/8/14 20:45
---

FirstCtrl={}
local this=FirstCtrl;

local message;
local transform;
local gameObject;

function FirstCtrl.New()
    logWarn("FirstCtrl.New---->>>");
    return this;
end

function FirstCtrl.Awake()
    logWarn("FirstCtrl.Awake---->>>");
    panelMgr:CreatePanel("First",this.OnCreate)
end

function FirstCtrl.OnCreate(obj)
    gameObject=obj;
    transform=gameObject.transform;

    --message=gameObject:GetComponent('LuaBehaviour');

    --点击事件
    behaviour=gameObject:GetComponent("LuaBehaviour");
    behaviour:AddClick(FirstPanel.btnClose,function ()
        print("点击关闭按钮")
    end)

    --加载prefabs.unity3d资源包
    resMgr:LoadPrefab("prefabs.unity3d",{"ImgOrc"},function (prefabs)
        log(prefabs.Length)
        log(prefabs[0].name)

        --加载ImgOrc到FirstPanel下
        --实例化
        local go=newObject(prefabs[0])
        --设置父对象
        go.transform:SetParent(transform)
        --设置初始位置
        go.transform.localPosition=Vector3.zero
        --设置缩放信息
        go.transform.localScale=Vector3.one
    end)
end

function FirstCtrl.OnClick(go)
    destroy(gameObject);
end

function FirstCtrl.Onclose()
    panelMgr:ClosePanel(CtrlNames.First)
end