---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 86181.
--- DateTime: 2021/8/15 20:15
---

local gameObject;
local transform;

LoginPanel={}
local this=LoginPanel;

function LoginPanel.Awake(obj)
    gameObject=obj;
    transform=gameObject.transform;
    log("登录面板1");
    this.InitPanel();
end

function LoginPanel.InitPanel()
    --账号输入框
    this.InputAccount=transform:Find("Account/InputAccount").gameObject;
    --密码输入框
    this.InputPwd=transform:Find("Pwd/InputPwd").gameObject;
    --登录按钮
    this.BtnLogin=transform:Find("BtnLogin").gameObject;
    --记住密码开关
    this.TogSavePwd=transform:Find("TogSavePwd").gameObject;
    log("登录面板2");
end

function LoginPanel.OnDestroy()

end