---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 86181.
--- DateTime: 2021/8/14 19:08
---

local transform;
local gameObject;

FirstPanel={}
local this=FirstPanel;

function FirstPanel.Awake(obj)
    gameObject=obj;
    transform=obj.transform;

    this.InitPanel();
    logWarn("Awake lua---->>>"..gameObject.name);
end

function FirstPanel.InitPanel()
    --关闭按钮
    this.btnClose=transform:Find('BtnClose').gameObject;
end

function FirstPanel.OnDestroy()
    logWarn("OnDestroy---->>>");
end
