---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 86181.
--- DateTime: 2021/8/15 20:15
---

LoginCtrl={}
local this=LoginCtrl;

local message;
local gameObject;
local transform;

function LoginCtrl.New()
    return this;
end

function LoginCtrl.Awake()
    panelMgr:CreatePanel("Login",this.OnCreate)
end

function LoginCtrl.OnCreate(obj)
    gameObject=obj;
    transform=gameObject.transform;
    log("登录控制器");
    --事件
    behaviour=gameObject:GetComponent("LuaBehaviour");
    behaviour:AddClick(LoginPanel.BtnLogin,function ()
        log("登录按钮点击")
    end)

    behaviour:AddInputEnd(LoginPanel.InputAccount,function (account)
        log("账号输入结束,账号" .. account);
    end)

    behaviour:AddInputEnd(LoginPanel.InputPwd, function(pwd)
        log("账号输入结束,密码" .. pwd);
    end)

    behaviour:AddToggle(LoginPanel.TogSavePwd,function (go,isOn)
        log("记住密码：" .. tostring(isOn));
    end)
end